//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BancosEF
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BancosEFContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BancosEFContainer usando la cadena de conexión encontrada en la sección 'BancosEFContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public BancosEFContainer() : base("name=BancosEFContainer", "BancosEFContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BancosEFContainer.
        /// </summary>
        public BancosEFContainer(string connectionString) : base(connectionString, "BancosEFContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BancosEFContainer.
        /// </summary>
        public BancosEFContainer(EntityConnection connection) : base(connection, "BancosEFContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Banco> Banco
        {
            get
            {
                if ((_Banco == null))
                {
                    _Banco = base.CreateObjectSet<Banco>("Banco");
                }
                return _Banco;
            }
        }
        private ObjectSet<Banco> _Banco;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Banco. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBanco(Banco banco)
        {
            base.AddObject("Banco", banco);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BancosEF", Name="Banco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Banco : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Banco.
        /// </summary>
        /// <param name="codigoBanco">Valor inicial de la propiedad CodigoBanco.</param>
        /// <param name="nombreBanco">Valor inicial de la propiedad NombreBanco.</param>
        /// <param name="direccionPrincipal">Valor inicial de la propiedad DireccionPrincipal.</param>
        /// <param name="nombreCiudad">Valor inicial de la propiedad NombreCiudad.</param>
        public static Banco CreateBanco(global::System.Int32 codigoBanco, global::System.String nombreBanco, global::System.String direccionPrincipal, global::System.String nombreCiudad)
        {
            Banco banco = new Banco();
            banco.CodigoBanco = codigoBanco;
            banco.NombreBanco = nombreBanco;
            banco.DireccionPrincipal = direccionPrincipal;
            banco.NombreCiudad = nombreCiudad;
            return banco;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodigoBanco
        {
            get
            {
                return _CodigoBanco;
            }
            set
            {
                if (_CodigoBanco != value)
                {
                    OnCodigoBancoChanging(value);
                    ReportPropertyChanging("CodigoBanco");
                    _CodigoBanco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodigoBanco");
                    OnCodigoBancoChanged();
                }
            }
        }
        private global::System.Int32 _CodigoBanco;
        partial void OnCodigoBancoChanging(global::System.Int32 value);
        partial void OnCodigoBancoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreBanco
        {
            get
            {
                return _NombreBanco;
            }
            set
            {
                OnNombreBancoChanging(value);
                ReportPropertyChanging("NombreBanco");
                _NombreBanco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreBanco");
                OnNombreBancoChanged();
            }
        }
        private global::System.String _NombreBanco;
        partial void OnNombreBancoChanging(global::System.String value);
        partial void OnNombreBancoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DireccionPrincipal
        {
            get
            {
                return _DireccionPrincipal;
            }
            set
            {
                OnDireccionPrincipalChanging(value);
                ReportPropertyChanging("DireccionPrincipal");
                _DireccionPrincipal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DireccionPrincipal");
                OnDireccionPrincipalChanged();
            }
        }
        private global::System.String _DireccionPrincipal;
        partial void OnDireccionPrincipalChanging(global::System.String value);
        partial void OnDireccionPrincipalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCiudad
        {
            get
            {
                return _NombreCiudad;
            }
            set
            {
                OnNombreCiudadChanging(value);
                ReportPropertyChanging("NombreCiudad");
                _NombreCiudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCiudad");
                OnNombreCiudadChanged();
            }
        }
        private global::System.String _NombreCiudad;
        partial void OnNombreCiudadChanging(global::System.String value);
        partial void OnNombreCiudadChanged();

        #endregion

    
    }

    #endregion

    
}
