//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.DetalleFacturas = new HashSet<DetalleFacturas>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal ValorTotal { get; set; }
        public string Ciudad { get; set; }
    
        public virtual ICollection<DetalleFacturas> DetalleFacturas { get; set; }
    }
}
