//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("VentasModel", "fk_detallefacturas_facturas", "Facturas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ventas.Facturas), "DetalleFacturas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ventas.DetalleFacturas), true)]

#endregion

namespace Ventas
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class VentasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto VentasEntities usando la cadena de conexión encontrada en la sección 'VentasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public VentasEntities() : base("name=VentasEntities", "VentasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto VentasEntities.
        /// </summary>
        public VentasEntities(string connectionString) : base(connectionString, "VentasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto VentasEntities.
        /// </summary>
        public VentasEntities(EntityConnection connection) : base(connection, "VentasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleFacturas> DetalleFacturas
        {
            get
            {
                if ((_DetalleFacturas == null))
                {
                    _DetalleFacturas = base.CreateObjectSet<DetalleFacturas>("DetalleFacturas");
                }
                return _DetalleFacturas;
            }
        }
        private ObjectSet<DetalleFacturas> _DetalleFacturas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Facturas> Facturas
        {
            get
            {
                if ((_Facturas == null))
                {
                    _Facturas = base.CreateObjectSet<Facturas>("Facturas");
                }
                return _Facturas;
            }
        }
        private ObjectSet<Facturas> _Facturas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleFacturas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleFacturas(DetalleFacturas detalleFacturas)
        {
            base.AddObject("DetalleFacturas", detalleFacturas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Facturas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFacturas(Facturas facturas)
        {
            base.AddObject("Facturas", facturas);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VentasModel", Name="DetalleFacturas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleFacturas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleFacturas.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="idFactura">Valor inicial de la propiedad IdFactura.</param>
        /// <param name="nombreProducto">Valor inicial de la propiedad NombreProducto.</param>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        /// <param name="precio">Valor inicial de la propiedad Precio.</param>
        public static DetalleFacturas CreateDetalleFacturas(global::System.Int32 id, global::System.Int32 idFactura, global::System.String nombreProducto, global::System.Int32 cantidad, global::System.Decimal precio)
        {
            DetalleFacturas detalleFacturas = new DetalleFacturas();
            detalleFacturas.Id = id;
            detalleFacturas.IdFactura = idFactura;
            detalleFacturas.NombreProducto = nombreProducto;
            detalleFacturas.Cantidad = cantidad;
            detalleFacturas.Precio = precio;
            return detalleFacturas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFactura
        {
            get
            {
                return _IdFactura;
            }
            set
            {
                OnIdFacturaChanging(value);
                ReportPropertyChanging("IdFactura");
                _IdFactura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdFactura");
                OnIdFacturaChanged();
            }
        }
        private global::System.Int32 _IdFactura;
        partial void OnIdFacturaChanging(global::System.Int32 value);
        partial void OnIdFacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreProducto
        {
            get
            {
                return _NombreProducto;
            }
            set
            {
                OnNombreProductoChanging(value);
                ReportPropertyChanging("NombreProducto");
                _NombreProducto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreProducto");
                OnNombreProductoChanged();
            }
        }
        private global::System.String _NombreProducto;
        partial void OnNombreProductoChanging(global::System.String value);
        partial void OnNombreProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Decimal _Precio;
        partial void OnPrecioChanging(global::System.Decimal value);
        partial void OnPrecioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "fk_detallefacturas_facturas", "Facturas")]
        public Facturas Facturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facturas>("VentasModel.fk_detallefacturas_facturas", "Facturas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facturas>("VentasModel.fk_detallefacturas_facturas", "Facturas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Facturas> FacturasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facturas>("VentasModel.fk_detallefacturas_facturas", "Facturas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Facturas>("VentasModel.fk_detallefacturas_facturas", "Facturas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VentasModel", Name="Facturas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Facturas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Facturas.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="valorTotal">Valor inicial de la propiedad ValorTotal.</param>
        /// <param name="ciudad">Valor inicial de la propiedad Ciudad.</param>
        public static Facturas CreateFacturas(global::System.Int32 id, global::System.DateTime fecha, global::System.Decimal valorTotal, global::System.String ciudad)
        {
            Facturas facturas = new Facturas();
            facturas.Id = id;
            facturas.Fecha = fecha;
            facturas.ValorTotal = valorTotal;
            facturas.Ciudad = ciudad;
            return facturas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ValorTotal
        {
            get
            {
                return _ValorTotal;
            }
            set
            {
                OnValorTotalChanging(value);
                ReportPropertyChanging("ValorTotal");
                _ValorTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValorTotal");
                OnValorTotalChanged();
            }
        }
        private global::System.Decimal _ValorTotal;
        partial void OnValorTotalChanging(global::System.Decimal value);
        partial void OnValorTotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "fk_detallefacturas_facturas", "DetalleFacturas")]
        public DetalleFacturas DetalleFacturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DetalleFacturas>("VentasModel.fk_detallefacturas_facturas", "DetalleFacturas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DetalleFacturas>("VentasModel.fk_detallefacturas_facturas", "DetalleFacturas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DetalleFacturas> DetalleFacturasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DetalleFacturas>("VentasModel.fk_detallefacturas_facturas", "DetalleFacturas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DetalleFacturas>("VentasModel.fk_detallefacturas_facturas", "DetalleFacturas", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
