//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkNow.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorcicle : Vehicle
    {
        public override decimal HourPrice
        {
            get { return 1100; }
        }

        public override decimal HalfHourPrice
        {
            get { return HourPrice * (decimal)0.5; }
        }
    }
}
