//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkNow.DataAccess
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Representation of the motorcicles that get into the parking
    /// </summary>
    /// <!-- Author: Jonathan Soto<theja29@hotmail.com>. For licensing, e-mail me -->
    public partial class Motorcicle : Vehicle
    {
        public override decimal HourPrice
        {
            get { return 1100; }
        }

        public override decimal HalfHourPrice
        {
            get { return HourPrice * (decimal)0.5; }
        }
    }
}
