//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkNow.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Parking
    {
        public int Id { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public int UserNationalId { get; set; }
        public string VehiclePlate { get; set; }

        [Browsable(false)]
        public virtual User User { get; set; }
        [Browsable(false)]
        public virtual Vehicle Vehicle { get; set; }

        public TimeSpan? TotalTime
        {
            get { return (OutDate ?? DateTime.Now) - InDate; }
        }

        public decimal Cost
        {
            get { return Vehicle.HourPrice * (decimal) Math.Ceiling(TotalTime.Value.TotalHours); }
        }
    }
}
